"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['PyText3.py']
DATA_FILES = ['prefs.py', 'syntaxhighlighting.py', 'themes.py', 'font.sav', 'theme.sav', 'images/icon.icns', 'images/settingsicon.icns']
OPTIONS = {}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
